#     ___              _ __
#    / _ |_____ ______(_) /____
#   / __ /_ / // / __/ / __/ -_)
#  /_/ |_/__|_,_/_/ /_/\__/\__/
#

Token: ''
autoPingCheck:
  enable: true
  interval: 260
  round: 2 # 2.1234 = 2.12
  saveToLog: true


shard:
  enable: false
  shard_id: 0
  shard_count: 0

Loader:
  mappingFile: 'mapping.json'
  events: true
  commands: true
  commandsGroup: true

  multilThread:
    enable: false
    thread: auto #1 ,2,... auto

other:
  debug: false